### ISSUE TITLE
D题好像没考虑到有大于m个2023的情况吧

### ISSUE THREAD

**Issue by H3AlO3** [shannany0606/14_Lanqiao_Cup#2]
题目要求是恰好
比如输入`12 2`
您的代码会计算`202320232023`这种情况，但这是不符合要求的

**Comment by shannany0606** [comment]
对的。
当时考场上就被这题卡了挺久，也没想出啥好做法，就糊了一个上去。
现在想来，这题应该用隔板法+容斥算法比较合适：
隔板法：n-4m个数字被m个隔板/2023隔开，即n-4m个数字分为可以为空的m+1组，相当于n-4m+m+1=n-3m+1个数分为不可以为空的m+1组（每个组预先放了1个），即n-3m个地方选m个地儿放m个隔板，故方案数为C(n-3m,m)；
容斥法：加上m个的方案数，减去m+1个的方案数，加上m+2个的方案数。。。以此类推

**Comment by shannany0606** [comment]
所以这题应该没拿几分吧。。。

**Comment by H3AlO3** [comment]
> 对的。 当时考场上就被这题卡了挺久，也没想出啥好做法，就糊了一个上去。 现在想来，这题应该用隔板法+容斥算法比较合适： 隔板法：n-4m个数字被m个隔板/2023隔开，即n-4m个数字分为可以为空的m+1组，相当于n-4m+m+1=n-3m+1个数分为不可以为空的m+1组（每个组预先放了1个），即n-3m个地方选m个地儿放m个隔板，故方案数为C(n-3m,m)； 容斥法：加上m个的方案数，减去m+1个的方案数，加上m+2个的方案数。。。以此类推

这个思路确实不错，但是算上计算组合数的时间的话，总的时间复杂度就到O(n^2)了吧，1e5的数据python未必过得去

**Comment by shannany0606** [comment]
> > 对的。 当时考场上就被这题卡了挺久，也没想出啥好做法，就糊了一个上去。 现在想来，这题应该用隔板法+容斥算法比较合适： 隔板法：n-4m个数字被m个隔板/2023隔开，即n-4m个数字分为可以为空的m+1组，相当于n-4m+m+1=n-3m+1个数分为不可以为空的m+1组（每个组预先放了1个），即n-3m个地方选m个地儿放m个隔板，故方案数为C(n-3m,m)； 容斥法：加上m个的方案数，减去m+1个的方案数，加上m+2个的方案数。。。以此类推
> 
> 这个思路确实不错，但是算上计算组合数的时间的话，总的时间复杂度就到O(n^2)了吧，1e5的数据python未必过得去

咳有道理，不过感觉容斥法也不好优化复杂度呀。。。看看有没有别的佬能讲讲吧

**Comment by H3AlO3** [comment]
我感觉我想明白了，隔板法算出来的是>=m的方案数，所以只要计算m个的然后减去m+1个的就好了，后面的没必要算

**Comment by shannany0606** [comment]
> 我感觉我想明白了，隔板法算出来的是>=m的方案数，所以只要计算m个的然后减去m+1个的就好了，后面的没必要算

哈哈好，鼠鼠就说蓝桥杯的题目应该没那么难，怪不得放D。谢谢啦
